/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */

export interface LoginInputDto {
  email: string;
  /** @minLength 8 */
  password: string;
}
