/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Openapi documentation
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterUserPayload {
  /**
   * @minLength 8
   * @pattern [A-Z]
   */
  confirmationPassword: string;
  email: string;
  firstName: string;
  lastName: string;
  /**
   * @minLength 8
   * @pattern [A-Z]
   */
  password: string;
}
